### ISSUE TITLE
Why can't it be extended into an iOS App?

### ISSUE THREAD

**Issue by KonstantinKostianytsia** [loloof64/React-Native-Stockfish-Android#3]
I don't have deep knowledge in native development and I'm curious why it can't be extended for iOS also. Are there some architecture problems?

**Comment by loloof64** [comment]
Hi ! It's simply that I don't own a Mac computer, and developping for IOS requires a Mac computer. That's it.

**Comment by KonstantinKostianytsia** [comment]
@loloof64 I see, I want to use your library for my pet project and I really want to make it work on iOS also. If I have some sucess on this issue I will let you know. Thank you!

**Comment by loloof64** [comment]
Thank you for your interest in my project, but it is unlikely that it is ported to IOS. Meanwhile, if you or if you know someone which can extends it with a Mac computer, I'll be very fine with that.
