### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by DawiQ** [loloof64/React-Native-Stockfish-Android#4]
Hi everyone :)
In the description of the MainLoop method, it mentions that the "quit" command should be sent when we are done. I think it would be beneficial to include this information in the README.md. If it was there, it would save me a lot of time, because I had a lot of issues with engine not working when used with react-navigation. But, when "quit" command is sent, everything works more than perfectly.

Thanks!
Dawid

**Comment by loloof64** [comment]
Hi ! Did you try rather to call `shutDownStockfish`, as in the snippet in the README ?
Because this call send quit to the engine.
